### ISSUE TITLE
Doesn't work w/ 8.1 with c# and xaml

### ISSUE THREAD

**Issue by stinethebean** [liveservices/LiveSDK#20]
Attempting to run this with version 5.4 of the live sdk and refactoring to 8.1 is a complete mess and doesn't work. (note all the  grey boxes are folders, but clicking on them does nothing)

![image](https://f.cloud.github.com/assets/5238880/1212256/6c373188-2615-11e3-8026-b5fe3760f725.png)

**Comment by peternied** [comment]
Trying to start the new year off with a clean start!
