### ISSUE TITLE
JsonWebToken sample is not working correctly

### ISSUE THREAD

**Issue by gilad61** [liveservices/LiveSDK#4]
In "LiveSDK/Samples/Asp.net/AuthenticationTokenSample/JsonWebToken.cs" there are two mistakes that make the signature validation fail:
1. In line 284 - the HMACSHA256 should be created using the 'signingKey' variable and not 'bytes'.
2. In line 260 - the comment says to use key + "JWTSIG", but the code only uses 'key'. In fact none of these work, and only when changed to key + "JWTSig" (with lowercase 'ig') the validation passes.

I am not sure what is the standard way to create the signing key, but it looks like the Live Connect service uses key + "JWTSig" to sign the token.
I also found a version of this validation code that does use "JWTSig" on MSDN forum - http://social.msdn.microsoft.com/Forums/en-US/messengerconnect/thread/0705264a-e306-4cfd-a007-017fd60b1f6a

**Comment by AllenConway** [comment]
The one main thing I found is to remove the appended "JWTSig" string from being appended to the master key in the ValidateSignature() method. It appears the tokens being signed no longer append that string to the master key anymore from AMS. I had issues getting the validation to pass until I removed that segment.

I believe it might have been in conjunction with the v1 JWT being deprecated from AMS as mentioned here: http://chrisrisner.com/Version-1-of-the-Mobile-Services-JWT-token-has-been-deprecated

I know I've been using this validation code to validate the JWT for the last couple years and it only recently stopped working when I got a new AMS instance. I'm not sure upon getting my new instance if any v1 tokens I was getting that were grandfathered were discontinued. At this point with my new AMS instance, the token would never validate until I removed that appended "JWTSig" from the master key. Does anyone know for certain if this process was indeed removed when MSFT signs those JWTs from AMS? Just trying to figure out definitively why it worked with that string and now I had to remove it for it to work again.
